# Generated by Django 4.0.3 on 2023-05-31 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('is_host', models.BooleanField(default=False)),
                ('is_part', models.BooleanField(default=False)),
                ('roles', models.CharField(choices=[('is_host', 'Host'), ('is_part', 'Participate')], default=models.BooleanField(default=False), max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', main.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, null=True)),
                ('files', models.FileField(blank=True, null=True, upload_to='images')),
                ('project_id', models.CharField(max_length=100, null=True)),
                ('team_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('title', models.CharField(max_length=100, null=True)),
                ('project_id', models.CharField(max_length=100, null=True)),
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_leader', models.CharField(max_length=100, null=True)),
                ('team_m2', models.CharField(max_length=100, null=True)),
                ('team_m3', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('organization', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_student', models.BooleanField(default=False)),
                ('is_employee', models.BooleanField(default=False)),
                ('roles', models.CharField(choices=[('is_student', 'Student'), ('is_employee', 'Employee')], default=models.BooleanField(default=False), max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('1', 'First Place'), ('2', 'Second Place'), ('3', 'Third Place')], max_length=1)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.details')),
            ],
        ),
        migrations.CreateModel(
            name='Host_hack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='images')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('org_name', models.CharField(max_length=200)),
                ('org_desc', models.TextField()),
                ('from_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('host_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
